//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuneWorldFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int ObjectId { get; set; }
        public string UserId { get; set; }
        public string ObjectName { get; set; }
        public string ObjectDesc { get; set; }
        public string ObjectUploadLink { get; set; }
        public string ObjectDownloadLink { get; set; }
        public string ObjectUpdateTime { get; set; }
        public bool MakePublic { get; set; }
        public string SongName { get; set; }
        public string Language { get; set; }
        public string Genre { get; set; }
    }
}
